apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 443868026692.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 443868026692.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: b28d92c6
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
